[Language Server] indexing scopes
tweag/nickel pull request #421
Opened 2021-10-15 14:58 UTC by ysndr

Track and collect scopes for linearized items

2021-11-03 10:19 UTC, yannham requested changes
If I understand correctly, you are representing scopes (that are morally a tree mimicking the structure of the AST where nodes corresponds to a local environment) as a map that associates a path from the root in this tree to a scope.

I guess there are others, maybe simpler and/or more efficient ways of doing this. One would be to store scope information in the linearization items themselves, avoiding the use of an  auxiliary data structure. A second one would be to use a tree representation directly instead of a hashmap (although that's not obviously better in term of performance, because of cache and all).

Anyway, performance is hard, and your approach is still reasonable, so let's wait to have some actual measurement before yak-shaving.

However, I couldn't compile the language server using using stable Rust. Please fix the compilation errors as well as warnings.

2021-11-03 10:20 UTC, yannham commented
By the way, you may have to rebase onto `master` to get rid of this macOS nix installation bug that affects the CI.

2021-11-04 12:44 UTC, ysndr commented
I resolved the comments you had @yannham, are you fine with this being merged?

2021-11-04 14:58 UTC, yannham commented on lsp/nls/src/linearization.rs
> +    /// Elements are reorderd to allow efficient lookup of elemts by
```suggestion
    /// Elements are reordered to allow efficient lookup of elements by
```

2021-11-04 15:00 UTC, yannham approved these changes

2021-11-04 15:00 UTC, merged