Use deep_repr when printing evaluated term
tweag/nickel pull request #538
Opened 2022-01-04 14:53 UTC by Avi-D-coder

fix: #524

2022-01-04 15:05 UTC, yannham requested changes
The output is not the same as for the `:p` command:

```
nickel> {foo = "bar", baz = "boo"}
{ baz = %886, foo = %885}

nickel> :p {foo = "bar", baz = "boo"}
{ baz = "boo", foo = "bar"}
```

I suspect the `:p` does a bit more magic, like getting rid of those automatically generated variables. We should probably do the same, otherwise it's just gonna print those `%XX` everywhere.

2022-01-04 15:13 UTC, Avi-D-coder commented
@yannham Print uses `eval_full`, is that an issue?

2022-01-04 17:34 UTC, yannham commented
Hmm. This means we are forcing the evaluation as well. Let me ask on the issue.

2022-01-05 09:27 UTC, yannham approved these changes

2022-01-05 09:27 UTC, merged