Write note on possible lossless parsers
tweag/nickel pull request #658
Opened 2022-03-15 11:00 UTC by ErinvanderVeen

I would like this PR to serve as a discussion for the recommendation and options laid out in the note, and options I failed to include.

2022-03-15 17:15 UTC, yannham reviewed
As a general question: being comment/newline-aware would indeed require to wrap many rules. Actually you don't need 4 rules per operation, but you do need some duplication. Also, we need to be careful not to introduce ambiguities: 
```nickel
(+)
 1 # foo
 2
```

Should `#foo` be associated with `1` or `2`? Or the whole application?

Something that is not totally clear though is how this issue would be solved by other technologies. Whatever formalism you use, you still have to specify that comments and newlines may be associated with some (many) elements of your grammar. If there is a reason why this is easier with, say, a PEG parser generator or parser combinators than with LALRPOP, then I think this deserves to be explained in this document.

2022-03-15 17:15 UTC, yannham commented on notes/lossless-ast-parsing.md
> +combinator library.
Another argument used usually against parser combinators is that they are not very efficient, but I don't know if that claim is fair in practice. I imagine that it depends a lot on the particular parser combinator library.

2022-03-16 07:56 UTC, ErinvanderVeen commented on notes/lossless-ast-parsing.md
> +Hence we can safely say rowan is likely suitable for nickel.
I will reword this section, but what I wanted to imply is that:
- rowan is used for quite a few programming tools (mainly language servers)
- at least one compiler

2022-03-16 08:10 UTC, ErinvanderVeen commented on notes/lossless-ast-parsing.md
> +Ungrammar is a grammar that works to construct the SyntaxNodes as described in
I have reworded this section to:

Ungrammar is "a ... formalism for describing concrete syntax trees". Concretely,
ungrammar takes a
[file written in its grammar](https://github.com/rust-analyzer/ungrammar/blob/master/rust.ungram)
and produces
[a file](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/syntax/src/ast/generated/nodes.rs)
that contains the functions (RedNodes) needed to interact with the GreenNodes
(typically produced by rowan). Ungrammar has seen limited/no use outside of
rust-analyzer, and I do not think Nickel would benefit greatly from it.

2022-03-16 08:22 UTC, aspiwack commented
What would be the advantage of using something like Ungrammar rather than writing your concrete syntax tree? It's not obvious to me.

2022-03-16 08:24 UTC, aspiwack commented
@tek You have experience with tree-sitter, maybe you have an opinion on whether a tree-sitter parser can be use as the actual front end for a language? This would most definitely reduce the complexity for this issue.

2022-03-16 14:37 UTC, ErinvanderVeen commented
> What would be the advantage of using something like Ungrammar rather than writing your concrete syntax tree? It's not obvious to me.

@aspiwack I have tried to clarify what ungrammar is used for, hopefully this clears it up.

2022-03-16 17:15 UTC, aspiwack commented
What difference do you make between a typed syntax tree and a untyped syntax tree?

PS: I think we should refrain from using the moniker AST (which stands for _Abstract_ Syntax Tree) here as we are speaking of _concrete_ syntax trees instead.

2022-03-17 11:02 UTC, ErinvanderVeen commented
In the most recent commit I have now made a glossary that defines the terms I use, and made the use of these terms consistent.

2022-03-18 16:33 UTC, milahu commented
> whether a tree-sitter parser can be use as the actual front end for a language?

related issue

* https://github.com/tree-sitter/tree-sitter/issues/1631
  * parse errors are not helpful
  * "Usually tree-sitter is used as a fast first-pass parser before the slower actual parser comes up with the syntax errors. I think there are benefits to keeping tree-sitter simple so grammars stay easy to write."
  * "Tree-sitter is also a syntax-only parser and does not have any capability for adding semantic analysis like variables not being defined or incorrect function arity; full parsers include these things with their error messages."

2022-04-07 10:25 UTC, yannham requested changes
I think those notes are useful to keep, and aren't really expected to change much by now. The main issue is probably the lack of update about the error reporting of tree-sitter, but once fixed, we should merge this.

2022-04-07 10:25 UTC, yannham commented on notes/lossless-ast-parsing.md
> +typically untyped.
```suggestion
- **Concrete Syntax Tree (CST)/Parse Tree**: A tree that results from parsing, and
represents the syntactic structure of a string/file. May be lossless/full
fidelity.
- **Abstract Syntax Tree (AST)**: A tree that represents the abstract syntactic
structure of a string/file. Used for further processing of the file. Not
lossless/full fidelity. 
- **Lossless/full fidelity**: A lossless CST is a tree that contains all information
to recreate the original string/file exactly.
- **Typed**: A Typed Syntax Tree is a tree where the type of the parent implies the
type of the children. Every node has a specific type, with specific fields,
nodes are not interchangeable. Most ASTs are typed.
- **Untyped**: An Untyped Syntax Tree is a tree where the type/kind of a parent node
does not force the type/kind of the children nodes. Lossless syntax trees are
typically untyped.
```

2022-04-07 10:25 UTC, yannham commented on notes/lossless-ast-parsing.md
> +(there is no place for comments in a typed tree. There are ways around this,
```suggestion
(there is no place for comments in a typed tree). There are ways around this,
```

2022-04-07 10:25 UTC, yannham commented on notes/lossless-ast-parsing.md
> +To this extend they created two libraries specifically for
```suggestion
To this extent they created two libraries specifically for
```

2022-04-07 10:25 UTC, yannham commented on notes/lossless-ast-parsing.md
> +I don't see a fundamental problem that would stop us from using tree-sitter as
Now I think you can add something about error reporting being too limited.

2022-04-21 12:48 UTC, yannham commented
ping @ErinvanderVeen

2022-04-21 13:24 UTC, ErinvanderVeen commented
Will be updated. But need to figure out how to word Xavier's approach.

2022-05-11 10:53 UTC, merged