bench stdlib typechecking
tweag/nickel pull request #712
Opened 2022-05-25 08:43 UTC by francois-caddet

As part of the intent to bench the typechecker, this PR add a bench of stdlib.
It should as possible only bench the typechecking phase and not the previous ones (loading and parsing).

2022-05-25 16:09 UTC, yannham requested changes
The time measurement is suspiciously low (in the order of hundreds of microseconds). I suspect that typechecking is only done the first time, and then subsequent calls to `self.typecheck` do nothing because the state of the entries corresponding to the stdlib is `TYPECHECKED`, which invalidates criterion's measurements.

2022-05-25 16:09 UTC, yannham commented on src/cache.rs
> +    /// Internal function to typecheck stdlib. Has to be public because it's used in benches.
Nitpick: if it's public, it's not totally internal :stuck_out_tongue: so maybe a short description could be added, like "Typecheck the stdlib, provided the initial typing environment."

2022-05-25 16:15 UTC, yannham approved these changes
My bad, I don't think this is the case in the end, because you clone the initial cache at each iteration. For comparison the other typechecking bench is the order of a few microseconds, which is a huge difference. So it seems typechecking is just that fast on small programs.

2022-05-30 08:25 UTC, francois-caddet commented
Yes, I noticed that also. But I actualy think it's correct. As you said, the cache is cloned at each iteration and the type_env is not mutable. So we should not have the typechecking cached. Just be happy, your typechecker is so fast ;)

2022-05-30 10:54 UTC, merged